CREATE TABLE auth_users (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    login varchar(32) NOT NULL UNIQUE,
    password varchar(254) NOT NULL,
    name varchar(32) NOT NULL,
    email varchar(254),
    scope jsonb NOT NULL DEFAULT '[]',
    ip_register inet,
    registered timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    activate_key varchar(64),
    activated timestamptz,
    updated timestamptz,
    disabled boolean NOT NULL DEFAULT false
);
COMMENT ON TABLE auth_users IS 'Пользователи системы';

CREATE TABLE auth_server (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    client_id varchar(32) NOT NULL UNIQUE,
    client_secret varchar(32) NOT NULL,
    redirect_uris varchar(254)[],
    user_id bigint REFERENCES auth_users (id)
);
COMMENT ON TABLE auth_server IS 'Клиенты сервера OAuth 2.0';

CREATE TABLE auth_tokens (
    code varchar(32) NOT NULL UNIQUE,
    access_token varchar(32) UNIQUE,
    expires_in interval DEFAULT '3600 seconds',
    refresh_token varchar(32) UNIQUE,
    client_id bigint REFERENCES auth_server (id),
    user_id bigint REFERENCES auth_users (id),
    scope text,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE auth_tokens IS 'Токены OAuth 2.0';

CREATE TABLE auth_sessions (
    uid varchar(32) NOT NULL UNIQUE,
    token varchar(32) NOT NULL UNIQUE,
    expires timestamptz NOT NULL,
    user_entity text NOT NULL,
    ip inet,
    browser text,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX auth_sessions_expires_idx ON auth_sessions (expires);
COMMENT ON TABLE auth_sessions IS 'Сессии пользователей системы';

CREATE TABLE auth_fail2ban (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    login varchar(32) NOT NULL,
    ip inet NOT NULL,
    fail_time timestamptz NOT NULL
);
CREATE INDEX auth_fail2ban_login_idx ON auth_fail2ban (login);
CREATE INDEX auth_fail2ban_fail_time_idx ON auth_fail2ban (fail_time);
COMMENT ON TABLE auth_fail2ban IS 'Данные об ошибках аутентификации';