CREATE TABLE auth_users (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    login varchar(32) NOT NULL UNIQUE,
    password varchar(254) NOT NULL,
    name varchar(32) NOT NULL,
    email varchar(254),
    scope jsonb NOT NULL DEFAULT '[]',
    ip_register inet,
    registered timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    activate_key varchar(64),
    activated timestamptz,
    updated timestamptz,
    disabled boolean NOT NULL DEFAULT false
);
COMMENT ON TABLE auth_users IS 'Пользователи системы';

CREATE TABLE auth_server (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    client_id varchar(32) NOT NULL UNIQUE,
    client_secret varchar(32) NOT NULL,
    redirect_uris varchar(254)[],
    user_id bigint REFERENCES auth_users (id)
);
COMMENT ON TABLE auth_server IS 'Клиенты сервера OAuth 2.0';

CREATE TABLE auth_tokens (
    code varchar(32) NOT NULL UNIQUE,
    access_token varchar(32) UNIQUE,
    expires_in interval DEFAULT '3600 seconds',
    refresh_token varchar(32) UNIQUE,
    client_id bigint REFERENCES auth_server (id),
    user_id bigint REFERENCES auth_users (id),
    scope text,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE auth_tokens IS 'Токены OAuth 2.0';
