CREATE TABLE places (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    pid bigint REFERENCES places(id),
    name text NOT NULL
);
COMMENT ON TABLE places IS 'Места размещения устройств';

CREATE TABLE devices (
    uid varchar NOT NULL UNIQUE,
    hwid varchar NOT NULL UNIQUE,
    description text,
    entity jsonb,
    place_id bigint REFERENCES places(id)
);
COMMENT ON TABLE devices IS 'Физические устройства';

CREATE TABLE meters (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uid varchar NOT NULL UNIQUE,
    place_id bigint REFERENCES places(id),
    description text,
    unit varchar NOT NULL,
    device_property varchar UNIQUE,
    history boolean DEFAULT false
);
COMMENT ON TABLE meters IS 'Измерители';

CREATE TABLE meter_history (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    meter_id bigint REFERENCES meters(id),
    value float NOT NULL,
    timestamp timestamptz DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE meter_history IS 'Журнал измерений';
CREATE INDEX "meter_history_timestamp" ON "meter_history" ("timestamp");

CREATE TABLE indicators (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uid varchar NOT NULL UNIQUE,
    place_id bigint REFERENCES places(id),
    description text,
    device_property varchar UNIQUE,
    history boolean DEFAULT false
);
COMMENT ON TABLE indicators IS 'Контрольные датчики';

-- История срабатывания датчиков сигнализации устройств
CREATE TABLE indicator_history (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    indicator_id bigint REFERENCES indicators(id),
    value boolean NOT NULL,
    timestamp timestamptz DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE indicator_history IS 'Журнал контрольных датчиков';
CREATE INDEX "indicator_history_timestamp" ON "indicator_history" ("timestamp");

CREATE TABLE variables (
    name varchar NOT NULL UNIQUE,
    value text
);
COMMENT ON TABLE variables IS 'Пользовательские и системные переменные';
